version: "3.9"

services:
  db:
    image: postgres:16
    container_name: rhino_db
    restart: always
    environment:
      POSTGRES_USER: rhino
      POSTGRES_PASSWORD: rhino
      POSTGRES_DB: rhino_db
    ports:
      - "5445:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: